# Docker Compose for Redis DB
version: '3'
services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    container_name: redis-stack
    restart: always
